language: ruby
rvm:
  - 2.1.2
services:
  - mysql
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - RAILS_ENV=test bundle exec rake dev:bootstrap --trace
script:
  - 'bundle exec rspec --color --format documentation'
