language: ruby
rvm:
  - 2.1.1
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: 
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/secrets.yml.example config/secrets.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace  
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
  - script/wait_for_solr.sh 8981
after_script: RAILS_ENV=test bundle exec rake sunspot:solr:stop
